# Generated by Django 3.0.6 on 2020-05-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_paterno', models.CharField(max_length=20, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(max_length=20, verbose_name='Apellido materno')),
                ('nombres', models.CharField(max_length=20, verbose_name='Nombre(s)')),
                ('nacimiento', models.DateField()),
                ('edad', models.PositiveIntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Fememnino')], max_length=1, verbose_name='Sexo')),
                ('curp', models.CharField(max_length=18, verbose_name='Curp')),
                ('telefono', models.PositiveIntegerField(verbose_name='Telefono de casa')),
                ('celular', models.PositiveIntegerField(verbose_name='Celular')),
                ('tel_recado', models.PositiveIntegerField(verbose_name='Telefono de contacto')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo eléctronico')),
                ('calle_numero', models.CharField(max_length=50, verbose_name='Calle y numero')),
                ('colonia', models.CharField(max_length=20, verbose_name='Colonia')),
                ('municipio', models.CharField(max_length=20, verbose_name='Municipio')),
                ('estado', models.CharField(max_length=15, verbose_name='Estado')),
                ('c_postal', models.CharField(max_length=5, verbose_name='Código postal')),
                ('matricula', models.PositiveIntegerField(verbose_name='Matricula')),
                ('f_ingreso', models.DateField(auto_now=True)),
                ('f_baja', models.DateField()),
                ('pago', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
            },
        ),
    ]
