# Generated by Django 3.0.6 on 2020-05-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0002_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='colonia',
            field=models.CharField(max_length=30, verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='f_baja',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='colonia',
            field=models.CharField(max_length=30, verbose_name='Colonia'),
        ),
    ]
