# Generated by Django 3.0.6 on 2020-05-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0004_auto_20200509_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='matricula',
            field=models.CharField(max_length=10, verbose_name='Matricula'),
        ),
    ]
