# Generated by Django 3.0.6 on 2020-05-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0006_auto_20200509_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='f_baja',
            field=models.DateField(),
        ),
    ]
