# Generated by Django 3.0.6 on 2020-05-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=60, verbose_name='Nombre'),
        ),
    ]
