# Generated by Django 3.0.6 on 2020-05-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0002_alumno_nombre_completo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='matricula',
            field=models.CharField(max_length=10, unique=True, verbose_name='Matricula'),
        ),
    ]
